from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from expenses.views import ExpenseViewSet

# Create DRF router
router = DefaultRouter()
router.register(r'expenses', ExpenseViewSet, basename='expense')

urlpatterns = [
    path('admin/', admin.site.urls),

    # API routes generated by the router
    path('api/', include(router.urls)),
]
